Vastly improved rbenv installer script

diff --git a/bin/dcp-install-rbenv b/bin/dcp-install-rbenv
--- a/bin/dcp-install-rbenv
+++ b/bin/dcp-install-rbenv
@@ -1,23 +1,31 @@
 #!/usr/bin/env bash
 
+git_prefix="git://github.com/sstephenson"
+rbenv="$git_prefix/rbenv.git"
+ruby_build="$git_prefix/ruby-build.git"
 
-if [[ -d "$HOME/.rbenv" ]]; then
-  echo >&2 "Error! rbenv is already installed for this user!"
+if [[ $1 = "--system" ]]; then
+  prefix="/usr/local/rbenv"
+  user="root"
+else
+  prefix="$HOME/.rbenv"
+  user="$USER"
+fi
+
+if [[ -d "$prefix" ]]; then
+  echo >&2 "Error! rbenv is already installed at $prefix!"
   exit 1
 fi
 
-git_prefix="git://github.com/sstephenson"
-if [[ $1 = "--system" ]]; then
-  prefix="/usr/local/rbenv"
-  sudo git clone "$git_prefix/rbenv.git" "$prefix"
-  sudo mkdir -p "$prefix/plugins"
-  sudo git clone "$git_prefix/ruby-build.git" "$prefix/plugins/ruby-build"
-else
-  prefix="$HOME/.rbenv"
-  git clone "$git_prefix/rbenv.git" "$prefix"
-  mkdir -p "$prefix/plugins"
-  git clone "$git_prefix/ruby-build.git" "$prefix/plugins/ruby-build"
-fi
+sudo -u "$user" git clone "$git_prefix/rbenv.git" "$prefix"
+sudo -u "$user" mkdir -p "$prefix/plugins"
+sudo -u "$user" git clone "$git_prefix/ruby-build.git" "$prefix/plugins/ruby-build"
 
 echo
 echo "rbenv and ruby-build have been installed at $prefix!"
+
+unset prefix
+unset user
+unset git_prefix
+unset rbenv
+unset ruby_build
