Routine maintenance on dcp-mvn-init

diff --git a/bin/dcp-mvn-init b/bin/dcp-mvn-init
--- a/bin/dcp-mvn-init
+++ b/bin/dcp-mvn-init
@@ -2,26 +2,14 @@
 
 set -eo pipefail
 
-readonly MAVEN_VERSION="3.5.3"
-readonly ARCHETYPE_PRESETS=(                                    \
-  "org.apache.maven.archetypes:maven-archetype-quickstart:1.1"  \
-  "org.jetbrains.kotlin:kotlin-archetype-jvm:1.2.40"            \
-  "com.github.dpoggi:jee7-archetype:1.1"                        \
+readonly MAVEN_VERSION="3.6.3"
+readonly ARCHETYPE_PRESETS=(
+  "org.apache.maven.archetypes:maven-archetype-quickstart:1.1"
+  "org.jetbrains.kotlin:kotlin-archetype-jvm:1.3.70"
+  "com.github.dpoggi:jee7-archetype:1.1"
 )
 
-readonly KERNEL_NAME="$(uname -s)"
-
 declare SETTINGS_XML_PATH
-
-check_bin() {
-  while (($# > 0)); do
-    if ! command -v "$1" >/dev/null; then
-      printf >&2 "%s not found\n" "$1"
-      return 1
-    fi
-    shift
-  done
-}
 
 print_usage() {
   cat <<EOT
@@ -36,27 +24,23 @@ OPTIONS:
 ARCHETYPE PRESETS:
 EOT
 
-  local i
-  for i in "${!ARCHETYPE_PRESETS[@]}"; do
-    printf "  %s) %s\n" "$((i + 1))" "${ARCHETYPE_PRESETS[${i}]}"
+  local idx
+  for idx in "${!ARCHETYPE_PRESETS[@]}"; do
+    printf '  %s) %s\n' "$((idx + 1))" "${ARCHETYPE_PRESETS[${idx}]}"
   done
 }
 
 mktemp() {
+  local os_name
+  os_name="$(uname -s)"
+
   local template
-  case "${KERNEL_NAME}" in
-    Darwin)
-      template="mvn__$1"
-      ;;
-    Linux)
-      template="mvn__XXXXXX__$1"
-      ;;
+  case "${os_name}" in
+    Darwin) template="mvn__$1" ;;
+    Linux)  template="mvn__XXXXXX__$1" ;;
+    *)      printf 'Unsupported OS "%s".\n' "${os_name}" >&2; return 1
   esac
-  if [[ -z "${template}" ]]; then
-    printf >&2 "Unknown operating system %s\n" "${KERNEL_NAME}"
-    return 1
-  fi
-  
+
   command mktemp -q -t "${template}"
 }
 
@@ -65,8 +49,10 @@ mvn() {
 }
 
 write_settings_xml() {
-  local tmpfile="$(mktemp settings_xml)"
-  cat >"${tmpfile}" <<EOT
+  local tmpfile
+  tmpfile="$(mktemp settings_xml)"
+
+  cat >"${tmpfile}" <<EOS
 <?xml version="1.0" encoding="UTF-8"?>
 <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
@@ -90,29 +76,33 @@ write_settings_xml() {
     </profile>
   </profiles>
 </settings>
-EOT
-  printf "%s" "${tmpfile}"
+EOS
+
+  printf '%s\n' "${tmpfile}"
 }
 
 __archetype_resolve() {
   if [[ "$1" =~ ^[^:]+:[^:]+:[^:]+$ ]]; then
-    printf "%s" "$1"
-  elif [[ "$1" =~ ^[[:digit:]]+$ ]] &&
-       [[ "$1" -gt "0" && "$1" -le "${#ARCHETYPE_PRESETS[@]}" ]]; then
-    printf "%s" "${ARCHETYPE_PRESETS[$(($1 - 1))]}"
+    printf '%s\n' "$1"
+  elif [[ "$1" =~ ^[[:digit:]]+$ ]] && (($1 > 0 && $1 <= ${#ARCHETYPE_PRESETS[@]})); then
+    printf '%s\n' "${ARCHETYPE_PRESETS[$(($1 - 1))]}"
+  else
+    return 1
   fi
 }
 
 __archetype_find_generated_dir() {
-  local pomfile
-  while IFS='' read -d '' -r pomfile; do
-    printf "%s" "$(dirname "${pomfile}")"
+  local search_dir="$1"
+
+  local pom
+  while IFS='' read -d '' -r pom; do
+    printf '%s\n' "$(dirname "${pom}")"
     return
-  done < <(find "$1" -mindepth 2 \
-                     -maxdepth 2 \
-                     -type f \
-                     -name pom.xml \
-                     -print0 2>/dev/null)
+  done < <(
+    find "${search_dir}" -mindepth 2 -maxdepth 2 -type f -name pom.xml -print0 2>/dev/null
+  )
+
+  return 1
 }
 
 __archetype_move_generated_files() {
@@ -122,33 +112,33 @@ __archetype_move_generated_files() {
   local item
   while IFS='' read -d '' -r item; do
     mv "${item}" "${destination}"
-  done < <(find "${generated_dir}" -mindepth 1 \
-                                   -maxdepth 1 \
-                                   -print0 2>/dev/null)
+  done < <(
+    find "${generated_dir}" -mindepth 1 -maxdepth 1 -print0 2>/dev/null
+  )
 }
 
 __archetype_generate_gav() {
   local dir="$1"
+  local generated_dir
 
   pushd "${dir}" >/dev/null
+  {
+    if (($# > 1)); then
+      local group_id artifact_id version
 
-  if [[ "$#" -gt "1" ]]; then
-    local group_id artifact_id version
-    IFS=':' read -r group_id artifact_id version <<< "$2"
+      IFS=':' read -r group_id artifact_id version <<<"$2"
 
-    mvn archetype:generate -DarchetypeGroupId="${group_id}" \
-                           -DarchetypeArtifactId="${artifact_id}" \
-                           -DarchetypeVersion="${version}"
-  else
-    mvn archetype:generate
-  fi
-
+      mvn archetype:generate -DarchetypeGroupId="${group_id}" \
+                             -DarchetypeArtifactId="${artifact_id}" \
+                             -DarchetypeVersion="${version}"
+    else
+      mvn archetype:generate
+    fi
+  }
   popd >/dev/null
 
-  local generated_dir="$(__archetype_find_generated_dir "${dir}")"
-
-  if [[ ! -d "${generated_dir}" ]]; then
-    printf >&2 "Unable to find directory generated by archetype\n"
+  if ! generated_dir="$(__archetype_find_generated_dir "${dir}")"; then
+    printf 'Unable to find directory generated by archetype.\n' >&2
     return 1
   fi
 
@@ -158,15 +148,14 @@ __archetype_generate_gav() {
 }
 
 archetype_generate() {
-  if [[ "$#" -lt "2" ]]; then
+  if (($# < 2)); then
     __archetype_generate_gav "$1"
     return
   fi
 
-  local gav="$(__archetype_resolve "$2")"
-
-  if [[ -z "${gav}" ]]; then
-    printf >&2 "Invalid archetype %s, skipping generation\n" "$2"
+  local gav
+  if ! gav="$(__archetype_resolve "$2")"; then
+    printf 'Invalid archetype %s, skipping generation.\n' "$2" >&2
     return
   fi
 
@@ -174,15 +163,16 @@ archetype_generate() {
 }
 
 __mvnw_check_overwrite_existing() {
-  if [[ ! -e "$1/.mvn/wrapper" ]] &&
-     [[ ! -e "$1/mvnw" && ! -e "$1/mvnw.cmd" ]]; then
+  if [[ ! -e "$1/.mvn/wrapper" ]] && [[ ! -e "$1/mvnw" && ! -e "$1/mvnw.cmd" ]]; then
     return
   fi
 
-  printf >&2 "Existing Maven wrapper detected. Overwrite (y/n)? "
-  read -r
+  printf 'Existing Maven wrapper detected. Overwrite (y/n)? ' >&2
 
-  if [[ "${REPLY}" =~ ^[Yy] ]]; then
+  local response
+  read -r response
+
+  if [[ "${response}" =~ ^[Yy] ]]; then
     rm -rf "$1/.mvn/wrapper" "$1/mvnw" "$1/mvnw.cmd"
   else
     return 1
@@ -195,7 +185,9 @@ mvnw_generate() {
   fi
 
   pushd "$1" >/dev/null
-  mvn -N io.takari:maven:wrapper -Dmaven="${MAVEN_VERSION}"
+  {
+    mvn -N io.takari:maven:wrapper -Dmaven="${MAVEN_VERSION}"
+  }
   popd >/dev/null
 
   # Permissions on these come out all kinds of wrong
@@ -203,8 +195,11 @@ mvnw_generate() {
   chmod 644 "$1/mvnw.cmd" "$1/.mvn/wrapper"/maven-wrapper.{jar,properties}
 
   # Zap annoying extra echo in Unix wrapper script
-  local tmpfile="$(mktemp mvnw)"
+  local tmpfile
+  tmpfile="$(mktemp mvnw)"
+
   sed -e '/^[[:space:]]*echo \$MAVEN_PROJECTBASEDIR$/d' "$1/mvnw" >"${tmpfile}"
+
   cat "${tmpfile}" >"$1/mvnw"
   rm -f "${tmpfile}"
 }
@@ -214,10 +209,12 @@ __git_check_overwrite_existing() {
     return
   fi
 
-  printf >&2 "Existing %s detected. Overwrite (y/n)? " "$(basename "$1")"
-  read -r
+  printf 'Existing %s detected. Overwrite (y/n)? ' "$(basename "$1")" >&2
 
-  if [[ "${REPLY}" =~ ^[Yy] ]]; then
+  local response
+  read -r response
+
+  if [[ "${response}" =~ ^[Yy] ]]; then
     # It would be overwritten anyway, but remove it in case it's a link
     rm -f "$1"
   else
@@ -229,38 +226,36 @@ __git_cat() {
   if [[ -s "${HOME}/.dcp/share/git/$1" ]]; then
     cat "${HOME}/.dcp/share/git/$1"
   else
-    # This is assigned to a local var first so cURL returning > 0
-    # stops the whole process
-    local file_contents="$(
-      curl -fsSL "https://raw.githubusercontent.com/dpoggi/dcp/master/share/git/$1"
-    )"
-    printf "%s" "${file_contents}"
+    # This is assigned to a local var first so cURL returning > 0 stops the whole process
+    local file_contents
+    file_contents="$(curl -fsSL "https://raw.githubusercontent.com/dpoggi/dcp/master/share/git/$1")"
+
+    printf '%s\n' "${file_contents}"
   fi
 }
 
 git_generate() {
   if __git_check_overwrite_existing "$1/.gitattributes"; then
-    __git_cat maven.gitattributes >"$1/.gitattributes"
+    __git_cat "maven.gitattributes" >"$1/.gitattributes"
   fi
+
   if __git_check_overwrite_existing "$1/.gitignore"; then
-    __git_cat maven.gitignore >"$1/.gitignore"
+    __git_cat "maven.gitignore" >"$1/.gitignore"
   fi
 }
 
 main() {
-  local skip_archetype="false"
-  local skip_wrapper="false"
-  local skip_git="false"
   local -a archetypes
+  local skip_archetype="false" skip_wrapper="false" skip_git="false"
 
   while (($# > 0)); do
     case "$1" in
-      -h|--help)        print_usage; return   ;;
+      -h|--help)        print_usage; return ;;
       --skip-archetype) skip_archetype="true" ;;
-      --skip-wrapper)   skip_wrapper="true"   ;;
-      --skip-git)       skip_git="true"       ;;
+      --skip-wrapper)   skip_wrapper="true" ;;
+      --skip-git)       skip_git="true" ;;
       -*)
-        printf >&2 "Unknown option %s\n\n" "$1"
+        printf 'Unknown option "%s"\n\n' "$1" >&2
         print_usage >&2
         return 1
         ;;
@@ -269,27 +264,37 @@ main() {
     shift
   done
 
-  check_bin curl mvn
+  if ! command -v curl >/dev/null; then
+    printf 'curl not found.\n' >&2
+    return 1
+  fi
+  if ! command -v mvn >/dev/null; then
+    printf 'mvn not found.\n' >&2
+    return 1
+  fi
 
   SETTINGS_XML_PATH="$(write_settings_xml)"
   readonly SETTINGS_XML_PATH
 
+  trap 'printf "rm -f %s\\n" "${SETTINGS_XML_PATH}"; rm -f "${SETTINGS_XML_PATH}"' RETURN
+
   if ! "${skip_archetype}"; then
-    if ((${#archetypes[@]} > 1)); then
-      printf >&2 "Specifying multiple archetypes is not supported\n\n"
+    if ((${#archetypes[@]} == 1)); then
+      archetype_generate . "${archetypes[0]}"
+    else
+      printf 'Exactly one archetype may be specified.\n\n' >&2
       print_usage >&2
       return 1
     fi
-    archetype_generate . "${archetypes[@]}"
   fi
+
   if ! "${skip_wrapper}"; then
     mvnw_generate .
   fi
+
   if ! "${skip_git}"; then
     git_generate .
   fi
-
-  rm -f "${SETTINGS_XML_PATH}"
 }
 
 main "$@"
