Total bin script overhaul

diff --git a/bin/dcp-bootstrap b/bin/dcp-bootstrap
--- a/bin/dcp-bootstrap
+++ b/bin/dcp-bootstrap
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
+fail() {
+  echo >&2 "$@"
+  exit 1
+}
+
 # Freak out and quit if we don't have Git and/or cURL.
-hash git 2>&- || { echo >&2 "We need Git first, cap'n!"; exit 1; }
-hash curl 2>&- || { echo >&2 "We need cURL first, cap'n!"; exit 1; }
+hash git 2>&- || fail "Error: git must be installed"
+hash curl 2>&- || fail "Error: curl must be installed"
 
 # Install directories
 omz_dir="${HOME}/.oh-my-zsh"
@@ -14,7 +19,7 @@ vim_dir="${HOME}/.vim"
 # If it's me, I want to be able to change my dotfiles,
 # otherwise clone the public repos.
 git_prefix="https://github.com/dpoggi"
-[[ "${ITS_ME}" ]] && git_prefix="git@github.com:dpoggi"
+[[ -n "${DCP_YEAH_YOU_KNOW_ME}" ]] && git_prefix="git@github.com:dpoggi"
 
 # Clone my fork of oh-my-zsh
 if [[ ! -e "${omz_dir}" ]]; then
@@ -57,11 +62,3 @@ else
   echo "cd ~/.vim/bundle/command-t && rake make"
   echo "Make sure you're set up to use the system Ruby first."
 fi
-
-unset action
-unset do_links
-unset omz_dir
-unset syntax_dir
-unset dcp_dir
-unset vim_dir
-unset git_prefix
diff --git a/bin/dcp-install-rbenv b/bin/dcp-install-rbenv
--- a/bin/dcp-install-rbenv
+++ b/bin/dcp-install-rbenv
@@ -1,31 +1,51 @@
 #!/usr/bin/env bash
 
-git_prefix="https://github.com/sstephenson"
-rbenv="${git_prefix}/rbenv.git"
-ruby_build="${git_prefix}/ruby-build.git"
+fail() {
+  echo >&2 "$@"
+  exit 1
+}
+
+[[ "${UID}" -gt "0" ]] ||
+  fail "Error: this script is meant to be run as an unprivileged user"
 
 if [[ "$1" = "--system" ]]; then
+  [[ -n "$(type -P lsb_release)" && "$(lsb_release -si)" = "Ubuntu" ]] ||
+    fail "Error: this script only supports the --system option on Ubuntu"
+
+  sudo_cmd="sudo"
   prefix="/usr/local/rbenv"
-  user="root"
 else
   prefix="${HOME}/.rbenv"
-  user="${USER}"
 fi
 
-if [[ -d "${prefix}" ]]; then
-  echo >&2 "Error! rbenv is already installed at ${prefix}!"
-  exit 1
-fi
+[[ -e "${prefix}" ]] &&
+  fail "Error: ${prefix} already exists"
 
-sudo -u "$user" git clone "${git_prefix}/rbenv.git" "${prefix}"
-sudo -u "$user" mkdir -p "${prefix}/plugins"
-sudo -u "$user" git clone "${git_prefix}/ruby-build.git" "${prefix}/plugins/ruby-build"
+sstephenson="https://github.com/sstephenson"
+rbenv="${sstephenson}/rbenv.git"
+ruby_build="${sstephenson}/ruby-build.git"
+
+${sudo_cmd} git clone "${rbenv}" "${prefix}"
+${sudo_cmd} mkdir -p "${prefix}/plugins"
+${sudo_cmd} git clone "${ruby_build}" "${prefix}/plugins/ruby-build"
+
+if [[ -n "${sudo_cmd}" ]]; then
+  ${sudo_cmd} usermod -a -G staff "${USER}"
+  ${sudo_cmd} chown -R root:staff "${prefix}"
+  ${sudo_cmd} chmod -R g+rwxXs "${prefix}"
+
+  rc_script="/etc/profile.d/rbenv.sh"
+  cat <<EOF | ${sudo_cmd} tee ${rc_script} >/dev/null
+if [ -d "/usr/local/rbenv" ] && [ ! -d "\$HOME/.rbenv" ]; then
+  export RBENV_ROOT="/usr/local/rbenv"
+  export PATH="\$RBENV_ROOT/bin:\$PATH"
+  eval "\$(rbenv init -)"
+fi
+EOF
+  cat <<EOF | ${sudo_cmd} tee -a /etc/zsh/zshenv >/dev/null
+  [[ -s "${rc_script}" ]] && source "${rc_script}"
+EOF
+fi
 
 echo
 echo "rbenv and ruby-build have been installed at ${prefix}!"
-
-unset prefix
-unset user
-unset git_prefix
-unset rbenv
-unset ruby_build
diff --git a/bin/dcp-pushover b/bin/dcp-pushover
--- a/bin/dcp-pushover
+++ b/bin/dcp-pushover
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-conf="${DCP}/conf/pushover"
+fail() {
+  echo >&2 "$@"
+  exit 1
+}
 
-[[ -e "${conf}" ]] ||
-  { echo >&2 "Error: must use ~/.dcp/conf/pushover to set \$PUSHOVER_TOKEN and \$PUSHOVER_USER."; exit 1; }
-[[ "$#" -lt "1" ]] &&
-  { echo >&2 "Usage: $(basename $0) 'message'"; exit 1; }
+config="${HOME}/.dcp/conf/pushover"
+if [[ ! -e "${config}" ]]; then
+  printf >&2 "Error: ~/.dcp/conf/pushover is missing, "
+  fail "need it to set \$PUSHOVER_TOKEN and \$PUSHOVER_USER"
+fi
+source "${config}"
 
-source "${conf}"
+[[ "$#" -ge "1" ]] ||
+  fail "Usage: $(basename "$0") 'message'"
+
 curl -s --data "token=${PUSHOVER_TOKEN}&user=${PUSHOVER_USER}&message=$1" https://api.pushover.net/1/messages.json
-
-unset conf
diff --git a/bin/dcp-transcode b/bin/dcp-transcode
--- a/bin/dcp-transcode
+++ b/bin/dcp-transcode
@@ -1,36 +1,31 @@
 #!/usr/bin/env bash
 
-hash ffmpeg 2>&-
-if [[ "$?" -ne "0" ]]; then
-  echo >&2 "Error: Need ffmpeg installed to continue!"
-  if [[ "$(uname)" = "Darwin" ]]; then
-    echo >&2 "You're on a Mac, you should install it from Homebrew."
-
-    hash brew 2>&-
-    if [[ $? -eq 0 ]]; then
-      read -p "You have Homebrew installed. Would you like to install ffmpeg now? (y/n) " -n 1 -r
-      echo
-      [[ "${REPLY}" =~ ^[Yy]$ ]] && { brew update && brew install ffmpeg; }
-    fi
-  fi
-
+fail() {
+  echo >&2 "$@"
   exit 1
-fi
+}
+
+ffmpeg() {
+  local ffmpeg_bin="$(type -P ffmpeg)"
+  [[ -x "${ffmpeg_bin}" ]] || fail "Error: ffmpeg must be installed"
+
+  "${ffmpeg_bin}" -i "$1" -strict experimental -c:v copy -c:a aac -cutoff 20000 -ac 2 -b:a 160k "$2"
+}
 
 convert() {
-  local base="${1%.*}"
-  local ext="${1##*.}"
+  local base="${1%.*}" ext="${1##*.}"
 
   if [[ "${ext}" = "mp4" ]]; then
-    ffmpeg -i "$1" -strict experimental -c:v copy -c:a aac -cutoff 20000 -ac 2 -b:a 160k "${base}.transcode.mp4"
+    ffmpeg "$1" "${base}.transcode.mp4"
   else
     if [[ -e "${base}.mp4" ]]; then
       echo >&2 "Error: ${base}.mp4 already exists, skipping."
     else
-      ffmpeg -i "$1" -strict experimental -c:v copy -c:a aac -cutoff 20000 -ac 2 -b:a 160k "${base}.mp4"
+      ffmpeg "$1" "${base}.mp4"
     fi
   fi
 }
+
 
 if [[ "$#" -eq "0" ]]; then
   for mkv in *.mkv; do
@@ -39,8 +34,6 @@ if [[ "$#" -eq "0" ]]; then
 
     convert "${mkv}"
   done
-
-  unset mkv
 else
   if [[ "$1" = "--help" ]]; then
     cat >&2 <<END
diff --git a/bin/dcp-update-npm b/bin/dcp-update-npm
--- a/bin/dcp-update-npm
+++ b/bin/dcp-update-npm
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 
+fail() {
+  echo >&2 "$@"
+  exit 1
+}
+
 [[ "$(uname)" = "Darwin" ]] ||
-  { echo >&2 "Error: this script is only for use on Mac OS X!"; exit 1; }
+  fail "Error: this script is only for use on Mac OS X!"
 [[ -d "/usr/local/Cellar/node" ]] ||
-  { echo >&2 "Error: Node is not installed through Homebrew!"; exit 1; }
+  fail "Error: Node is not installed through Homebrew!"
 
 for category in 1 3 5 7; do
   ln -sf /usr/local/lib/node_modules/npm/man/man${category}/* /usr/local/share/man/man${category}
diff --git a/bin/dcp-update-rbenv b/bin/dcp-update-rbenv
--- a/bin/dcp-update-rbenv
+++ b/bin/dcp-update-rbenv
@@ -1,15 +1,14 @@
 #!/usr/bin/env bash
 
-if [[ ! -d "${HOME}/.rbenv/bin" ]]; then
-  echo >&2 "Error! rbenv isn't installed in ${HOME}!"
-  exit 1
-else
-  cd "${HOME}/.rbenv"
+[[ -d "${HOME}/.rbenv/bin" ]] ||
+  { echo >&2 "Error: rbenv is not installed at ${HOME}/.rbenv"; exit 1; }
+
+cd "${HOME}/.rbenv"
+git fetch origin
+git rebase origin/master
+
+if [[ -d "${HOME}/.rbenv/plugins/ruby-build" ]]; then
+  cd "${HOME}/.rbenv/plugins/ruby-build"
   git fetch origin
   git rebase origin/master
-  if [[ -d "${HOME}/.rbenv/plugins/ruby-build" ]]; then
-    cd "${HOME}/.rbenv/plugins/ruby-build"
-    git fetch origin
-    git rebase origin/master
-  fi
 fi
