tweakin' the gifs

diff --git a/bin/dcp-gif b/bin/dcp-gif
--- a/bin/dcp-gif
+++ b/bin/dcp-gif
@@ -1,7 +1,11 @@
 #!/usr/bin/env bash
 #
-# From http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
+# dcp-gif - creates an animated GIF from a video file, with options for time
+# boundaries, dithering algorithms, resolution, and framerate.
 #
+# Adapted from http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
+#
+
 set -e
 
 log_info() {
@@ -17,8 +21,12 @@ log_error() {
 }
 
 print_usage() {
+  if [[ "$1" = "--prepend-newline" ]]; then
+    printf "\n"
+  fi
+
   cat <<EOT
-Usage: $(basename "$0") [options] <input>
+Usage: $(basename "$0") [options] <input file>
 
 OPTIONS:
   -h, --help                           Display this message
@@ -36,7 +44,7 @@ EOT
 
 main() {
   if ! hash ffmpeg 2> /dev/null; then
-    log_error "ffmpeg not found!"
+    log_error "Couldn't find ffmpeg. Make sure it's somewhere in PATH, then try again."
     return 1
   fi
 
@@ -44,6 +52,7 @@ main() {
   local scale="480"
   local start_time="00:00:00.000"
   local algorithm="floyd_steinberg"
+  local input_file
   while [[ "$#" -gt "0" ]]; do
     case "$1" in
       -h | --help)
@@ -72,42 +81,42 @@ main() {
         ;;
       -*)
         log_error "Unknown option: $1"
-        printf >&2 "\n"
-        print_usage >&2
+        print_usage --prepend-newline >&2
         return 1
         ;;
       *)
-        input="$1"
+        input_file="$1"
         ;;
     esac
     shift
   done
 
-  if [[ ! -e "${input}" ]]; then
-    log_error "No input file"
-    printf >&2 "\n"
-    print_usage >&2
+  if [[ ! -e "${input_file}" ]]; then
+    log_error "No input file."
+    print_usage --prepend-newline >&2
     return 1
   fi
 
-  output="${input%.*}.gif"
-  palette="${input%.*}.png"
+  local output_gif="${input_file%.*}.gif"
+  local palette="${input_file%.*}.png"
 
-  palette_opts="paletteuse=dither=${algorithm}"
-  filters="fps=${fps},scale=${scale}:-1:flags=lanczos"
-  time_opts="-ss ${start_time}"
+  local palette_opts="paletteuse=dither=${algorithm}"
+  local filters="fps=${fps},scale=${scale}:-1:flags=lanczos"
+  local time_opts="-ss ${start_time}"
   if [[ -n "${duration}" ]]; then
     time_opts="${time_opts} -t ${duration}"
   fi
 
   log_info "Generating palette..."
-  ffmpeg -v warning ${time_opts} -i "${input}" -vf "${filters},palettegen" -y "${palette}"
+  ffmpeg -v warning ${time_opts} -i "${input_file}" -vf "${filters},palettegen" -y "${palette}"
 
   log_info "Makin' the GIF..."
-  ffmpeg -v warning ${time_opts} -i "${input}" -i "${palette}" -lavfi "${filters} [x]; [x][1:v] ${palette_opts}" -y "${output}"
+  ffmpeg -v warning \
+         ${time_opts} \
+         -i "${input_file}" -i "${palette}" -lavfi "${filters} [x]; [x][1:v] ${palette_opts}" -y "${output_gif}"
 
-  log_info "Done."
   rm -f "${palette}"
+  log_info "Done."
 }
 
 main "$@"
