New Maven archetypes

diff --git a/bin/dcp-mvn-init b/bin/dcp-mvn-init
--- a/bin/dcp-mvn-init
+++ b/bin/dcp-mvn-init
@@ -6,6 +6,8 @@ readonly MAVEN_VERSION="3.5.0"
 readonly ARCHETYPE_PRESETS=(                                    \
   "org.apache.maven.archetypes:maven-archetype-quickstart:1.1"  \
   "org.apache.maven.archetypes:maven-archetype-webapp:1.0"      \
+  "org.jetbrains.kotlin:kotlin-archetype-jvm:1.1.3-2"           \
+  "org.jetbrains.kotlin:kotlin-archetype-js:1.1.3-2"            \
   "com.airhacks:javaee7-essentials-archetype:1.3"               \
 )
 
@@ -28,7 +30,7 @@ EOT
 
 assert_deps() {
   local dep
-  for dep in mvn curl; do
+  for dep in "$@"; do
     if ! command -v "${dep}" >/dev/null; then
       printf >&2 "%s not found\n" "${dep}"
       return 1
@@ -70,39 +72,40 @@ __archetype_move_generated_files() {
 }
 
 __archetype_generate_gav() {
+  local dir="$1"
   local group_id artifact_id version
-  IFS=':' read -r group_id artifact_id version <<< "$1"
+  IFS=':' read -r group_id artifact_id version <<< "$2"
 
   mvn archetype:generate -DarchetypeGroupId="${group_id}" \
                          -DarchetypeArtifactId="${artifact_id}" \
                          -DarchetypeVersion="${version}"
 
-  local generated_dir="$(__archetype_find_generated_dir .)"
+  local generated_dir="$(__archetype_find_generated_dir "${dir}")"
 
   if [[ ! -d "${generated_dir}" ]]; then
     printf >&2 "Unable to find directory generated by archetype\n"
     return 1
   fi
 
-  __archetype_move_generated_files "${generated_dir}" ./
+  __archetype_move_generated_files "${generated_dir}" "${dir}"/
 
   rmdir "${generated_dir}"
 }
 
 generate_archetype() {
-  local gav="$(__archetype_resolve "$1")"
+  local gav="$(__archetype_resolve "$2")"
 
   if [[ -z "${gav}" ]]; then
-    printf >&2 "Invalid archetype %s, skipping generation\n" "$1"
+    printf >&2 "Invalid archetype %s, skipping generation\n" "$2"
     return
   fi
 
-  __archetype_generate_gav "${gav}"
+  __archetype_generate_gav "$1" "${gav}"
 }
 
 __mvnw_check_overwrite_existing() {
-  if [[ ! -e "./.mvn/wrapper" ]] &&
-     [[ ! -e "./mvnw" && ! -e "./mvnw.cmd" ]]; then
+  if [[ ! -e "$1/.mvn/wrapper" ]] &&
+     [[ ! -e "$1/mvnw" && ! -e "$1/mvnw.cmd" ]]; then
     return
   fi
 
@@ -110,28 +113,30 @@ __mvnw_check_overwrite_existing() {
   read -r
 
   if [[ "${REPLY}" =~ ^[Yy] ]]; then
-    rm -rf ./.mvn/wrapper ./mvnw ./mvnw.cmd
+    rm -rf "$1/.mvn/wrapper" "$1/mvnw" "$1/mvnw.cmd"
   else
     return 1
   fi
 }
 
 generate_mvnw() {
-  if ! __mvnw_check_overwrite_existing; then
+  if ! __mvnw_check_overwrite_existing "$1"; then
     return
   fi
 
+  pushd "$1" >/dev/null
   mvn -N io.takari:maven:wrapper -Dmaven="${MAVEN_VERSION}"
+  popd >/dev/null
 
   # Permissions on these come out all kinds of wrong
-  chmod 644 ./mvnw.cmd ./.mvn/wrapper/maven-wrapper.{jar,properties}
+  chmod 644 "$1/mvnw.cmd" "$1/.mvn/wrapper"/maven-wrapper.{jar,properties}
 
   # Zap annoying extra echo in Unix wrapper script
-  sed -e '/^[[:space:]]*echo \$MAVEN_PROJECTBASEDIR$/d' ./mvnw >./mvnw.fixed
-  mv ./mvnw.fixed ./mvnw
+  sed -e '/^[[:space:]]*echo \$MAVEN_PROJECTBASEDIR$/d' "$1/mvnw" >"$1/mvnw.fixed"
+  mv "$1/mvnw.fixed" "$1/mvnw"
 
   # Fix permissions here too (now that it's been overwritten)
-  chmod 755 ./mvnw
+  chmod 755 "$1/mvnw"
 }
 
 __git_check_overwrite_existing() {
@@ -139,7 +144,7 @@ __git_check_overwrite_existing() {
     return
   fi
 
-  printf >&2 "Existing %s detected. Overwrite (y/n)? " "$1"
+  printf >&2 "Existing %s detected. Overwrite (y/n)? " "$(basename "$1")"
   read -r
 
   if [[ "${REPLY}" =~ ^[Yy] ]]; then
@@ -165,11 +170,11 @@ __git_cat() {
 }
 
 generate_git() {
-  if __git_check_overwrite_existing .gitattributes; then
-    __git_cat maven.gitattributes >.gitattributes
+  if __git_check_overwrite_existing "$1/.gitattributes"; then
+    __git_cat maven.gitattributes >"$1/.gitattributes"
   fi
-  if __git_check_overwrite_existing .gitignore; then
-    __git_cat maven.gitignore >.gitignore
+  if __git_check_overwrite_existing "$1/.gitignore"; then
+    __git_cat maven.gitignore >"$1/.gitignore"
   fi
 }
 
@@ -193,10 +198,10 @@ main() {
     shift
   done
 
-  assert_deps
+  assert_deps mvn curl
 
   if [[ "${#archetypes[@]}" -eq "1" ]]; then
-    generate_archetype "${archetypes[0]}"
+    generate_archetype . "${archetypes[0]}"
   elif [[ "${#archetypes[@]}" -gt "1" ]]; then
     printf >&2 "Specifying multiple archetypes is not supported\n\n"
     print_usage >&2
@@ -204,11 +209,11 @@ main() {
   fi
 
   if ! "${skip_wrapper}"; then
-    generate_mvnw
+    generate_mvnw .
   fi
 
   if ! "${skip_git}"; then
-    generate_git
+    generate_git .
   fi
 }
 
