More improvements to dcp-mvn-init

diff --git a/bin/dcp-mvn-init b/bin/dcp-mvn-init
--- a/bin/dcp-mvn-init
+++ b/bin/dcp-mvn-init
@@ -3,65 +3,73 @@
 set -eo pipefail
 
 readonly MAVEN_VERSION="3.5.0"
-readonly PRESET_ARCHETYPES=( \
-  "org.apache.maven.archetypes:maven-archetype-quickstart:1.1" \
-  "org.apache.maven.archetypes:maven-archetype-webapp:1.0" \
-  "com.airhacks:javaee7-essentials-archetype:1.3" \
+readonly ARCHETYPE_PRESETS=(                                    \
+  "org.apache.maven.archetypes:maven-archetype-quickstart:1.1"  \
+  "org.apache.maven.archetypes:maven-archetype-webapp:1.0"      \
+  "com.airhacks:javaee7-essentials-archetype:1.3"               \
 )
 
-usage() {
-  cat >&2 <<EOT
-Usage: $(basename "$0") [options] [(preset # | groupId:artifactId:version)]
+print_usage() {
+  cat <<EOT
+Usage: $(basename "$0") [options] [preset # or groupId:artifactId:version]
 
 OPTIONS:
-  -h, --help                             Display this message
-  --skip-wrapper                         Skip generating Maven wrapper
-  --skip-git                             Skip generating .git{attributes,ignore}
+  -h, --help                            Display this message
+  --skip-wrapper                        Skip generating Maven wrapper
+  --skip-git                            Skip generating .git{attributes,ignore}
 
-PRESET ARCHETYPES:
+ARCHETYPE PRESETS:
 EOT
-  local idx
-  for idx in "${!PRESET_ARCHETYPES[@]}"; do
-    printf >&2 "  %s) %s\n" "$(( ${idx} + 1 ))" "${PRESET_ARCHETYPES[${idx}]}"
+  local i
+  for i in "${!ARCHETYPE_PRESETS[@]}"; do
+    printf "  %s) %s\n" "$(( ${i} + 1 ))" "${ARCHETYPE_PRESETS[${i}]}"
   done
 }
 
 assert_deps() {
   local dep
-  for dep in mvn perl curl; do
-    if ! hash "${dep}" 2>/dev/null; then
+  for dep in mvn curl; do
+    if ! command -v "${dep}" >/dev/null; then
       printf >&2 "%s not found\n" "${dep}"
       return 1
     fi
   done
 }
 
-__archetype_find_generated() {
+__archetype_resolve() {
+  if [[ "$1" =~ ^[^:]+:[^:]+:[^:]+$ ]]; then
+    printf "%s" "$1"
+  elif [[ "$1" =~ ^[[:digit:]]+$ ]] &&
+       [[ "$1" -gt "0" && "$1" -le "${#ARCHETYPE_PRESETS[@]}" ]]; then
+    printf "%s" "${ARCHETYPE_PRESETS[$(( $1 - 1 ))]}"
+  fi
+}
+
+__archetype_find_generated_dir() {
   local pomfile
   while IFS='' read -d '' -r pomfile; do
     printf "%s" "$(dirname "${pomfile}")"
     return
-  done < <(find . -mindepth 2 -maxdepth 2 -type f -name pom.xml -print0 2>/dev/null)
+  done < <(find "$1" -mindepth 2 \
+                     -maxdepth 2 \
+                     -type f \
+                     -name pom.xml \
+                     -print0 2>/dev/null)
 }
 
-__archetype_move_generated() {
+__archetype_move_generated_files() {
+  local generated_dir="$1"
+  local destination="$2"
+
   local item
   while IFS='' read -d '' -r item; do
-    mv "${item}" ./
-  done < <(find "$1" -mindepth 1 -maxdepth 1 -print0 2>/dev/null)
+    mv "${item}" "${destination}"
+  done < <(find "${generated_dir}" -mindepth 1 \
+                                   -maxdepth 1 \
+                                   -print0 2>/dev/null)
 }
 
-__archetype_num_is_valid() { [[ "$1" -gt 0 && "$1" -le "${#PRESET_ARCHETYPES[@]}" ]]; }
-
-resolve_archetype() {
-  if [[ "$1" =~ ^[^:]+:[^:]+:[^:]+$ ]]; then
-    printf "%s" "$1"
-  elif [[ "$1" =~ ^[[:digit:]]+$ ]] && __archetype_num_is_valid "$1"; then
-    printf "%s" "${PRESET_ARCHETYPES[$(( $1 - 1 ))]}"
-  fi
-}
-
-generate_archetype() {
+__archetype_generate_gav() {
   local group_id artifact_id version
   IFS=':' read -r group_id artifact_id version <<< "$1"
 
@@ -69,89 +77,127 @@ generate_archetype() {
                          -DarchetypeArtifactId="${artifact_id}" \
                          -DarchetypeVersion="${version}"
 
-  local generated="$(__archetype_find_generated)"
+  local generated_dir="$(__archetype_find_generated_dir .)"
 
-  if [[ ! -d "${generated}" ]]; then
-    printf >&2 "Unable to find generated project"
+  if [[ ! -d "${generated_dir}" ]]; then
+    printf >&2 "Unable to find directory generated by archetype\n"
     return 1
   fi
 
-  __archetype_move_generated "${generated}"
+  __archetype_move_generated_files "${generated_dir}" ./
 
-  rmdir "${generated}"
+  rmdir "${generated_dir}"
 }
 
-__mvnw_check_existing() {
-  if [[ ! -d "./.mvn/wrapper" && ! -e "./mvnw" ]]; then
+generate_archetype() {
+  local gav="$(__archetype_resolve "$1")"
+
+  if [[ -z "${gav}" ]]; then
+    printf >&2 "Invalid archetype %s, skipping generation\n" "$1"
     return
   fi
 
-  printf >&2 "Existing Maven wrapper detected. Remove first (y/n)? "
+  __archetype_generate_gav "${gav}"
+}
+
+__mvnw_check_overwrite_existing() {
+  if [[ ! -e "./.mvn/wrapper" ]] &&
+     [[ ! -e "./mvnw" && ! -e "./mvnw.cmd" ]]; then
+    return
+  fi
+
+  printf >&2 "Existing Maven wrapper detected. Overwrite (y/n)? "
   read -r
 
-  if [[ "${REPLY}" = y* || "${REPLY}" = Y* ]]; then
-    rm -rf mvnw mvnw.cmd .mvn
+  if [[ "${REPLY}" =~ ^[Yy] ]]; then
+    rm -rf ./.mvn/wrapper ./mvnw ./mvnw.cmd
+  else
+    return 1
   fi
 }
 
 generate_mvnw() {
-  __mvnw_check_existing
+  if ! __mvnw_check_overwrite_existing; then
+    return
+  fi
 
   mvn -N io.takari:maven:wrapper -Dmaven="${MAVEN_VERSION}"
 
   # Permissions on these come out all kinds of wrong
-  chmod 755 ./mvnw
   chmod 644 ./mvnw.cmd ./.mvn/wrapper/maven-wrapper.{jar,properties}
 
   # Zap annoying extra echo in Unix wrapper script
-  perl -pi -e 's/^\s*echo \$MAVEN_PROJECTBASEDIR$//' ./mvnw
+  sed -e '/^[[:space:]]*echo \$MAVEN_PROJECTBASEDIR$/d' ./mvnw >./mvnw.fixed
+  mv ./mvnw.fixed ./mvnw
+
+  # Fix permissions here too (now that it's been overwritten)
+  chmod 755 ./mvnw
+}
+
+__git_check_overwrite_existing() {
+  if [[ ! -e "$1" ]]; then
+    return
+  fi
+
+  printf >&2 "Existing %s detected. Overwrite (y/n)? " "$1"
+  read -r
+
+  if [[ "${REPLY}" =~ ^[Yy] ]]; then
+    # Its contents would be overwritten anyway, but
+    # remove it in case it's a link
+    rm -f "$1"
+  else
+    return 1
+  fi
 }
 
 __git_cat() {
   if [[ -d "${HOME}/.dcp/share/git" ]]; then
     cat "${HOME}/.dcp/share/git/$1"
   else
-    curl -fsSL "https://raw.githubusercontent.com/dpoggi/dcp/master/share/git/$1"
+    curl -fsSL \
+         "https://raw.githubusercontent.com/dpoggi/dcp/master/share/git/$1"
   fi
 }
 
 generate_git() {
-  __git_cat maven.gitattributes >.gitattributes
+  if __git_check_overwrite_existing .gitattributes; then
+    __git_cat maven.gitattributes >.gitattributes
+  fi
 
-  __git_cat maven.gitignore >.gitignore
+  if __git_check_overwrite_existing .gitignore; then
+    __git_cat maven.gitignore >.gitignore
+  fi
 }
 
 main() {
   local skip_wrapper="false"
   local skip_git="false"
-  local archetype
+  local -a archetypes
 
   while (( $# > 0 )); do
     case "$1" in
-      -h|--help)      usage; return       ;;
+      -h|--help)      print_usage; return ;;
       --skip-wrapper) skip_wrapper="true" ;;
       --skip-git)     skip_git="true"     ;;
       -*)
         printf >&2 "Unknown option %s\n\n" "$1"
-        usage
+        print_usage >&2
         return 1
         ;;
-      *)              archetype="$1"
+      *)              archetypes+=("$1")
     esac
     shift
   done
 
   assert_deps
 
-  if [[ -n "${archetype}" ]]; then
-    local gav="$(resolve_archetype "${archetype}")"
-
-    if [[ -n "${gav}" ]]; then
-      generate_archetype "${gav}"
-    else
-      printf >&2 "Invalid archetype %s, skipping generation\n" \
-                 "${archetype}"
-    fi
+  if [[ "${#archetypes[@]}" -eq "1" ]]; then
+    generate_archetype "${archetypes[0]}"
+  elif [[ "${#archetypes[@]}" -gt "1" ]]; then
+    printf >&2 "Specifying multiple archetypes is not supported\n\n"
+    print_usage >&2
+    return 1
   fi
 
   if ! "${skip_wrapper}"; then
