Biiiiiig overhaul. Let's hope migration headaches are minimal.

diff --git a/bin/dcp-install-rvm b/bin/dcp-install-rvm
--- a/bin/dcp-install-rvm
+++ b/bin/dcp-install-rvm
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-hash curl 2>&- || { echo >&2 "Error! Couldn't find cURL or Wget!"; exit 1; }
-bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
+hash curl 2>&- || { echo >&2 "Error! Couldn't find cURL!"; exit 1; }
+curl -L https://get.rvm.io | bash -s stable
 if [[ -d "$HOME/.dcp" ]]; then
   cd "$HOME/.dcp"
   git checkout "dot/zshrc" "dot/bashrc" "dot/zlogin" "dot/bash_login"
