Another year, another YOLO

diff --git a/bin/yolo b/bin/yolo
--- a/bin/yolo
+++ b/bin/yolo
@@ -1,14 +1,34 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-git rev-parse --is-inside-work-tree >/dev/null 2>/dev/null
-if [[ "$?" != "0" ]]; then
-  printf >&2 "Fatal: not inside a Git work tree.\n"
-  exit 1
-fi
+set -e
 
-read -p "What's the motto? " -n 4 -r
-if [[ "${REPLY}" = "YOLO" ]]; then
-  printf >&2 "\n"
-  git commit --all --message="DEAL WITH IT"
-  git push --force origin master
-fi
+log_info() {
+  printf "\033[0;34m[%s]:\033[0m %s\n" \
+         "$(date "+%Y-%m-%d %H:%M:%S")" \
+         "$*"
+}
+
+log_error() {
+  printf >&2 "\033[1;37;41m[%s]:\033[0m %s\n" \
+             "$(date "+%Y-%m-%d %H:%M:%S")" \
+             "$*"
+}
+
+main() {
+  if ! git rev-parse --is-inside-work-tree &> /dev/null; then
+    log_error "Error: not inside a Git work tree"
+    return 1
+  fi
+
+  read -p "What's the motto (all caps)? " -n 4 -r
+
+  if [[ "${REPLY}" = "YOLO" ]]; then
+    printf >&2 "\n"
+
+    git commit --all --message="DEAL WITH IT"
+
+    git push origin +master
+  fi
+}
+
+main "$@"
